### ISSUE TITLE
Release 0.12.2?

### ISSUE THREAD

**Issue by Flyking001** [rust-lang-nursery/error-chain#292]
No stable version has been released for a long time since 0.11.0, Is there some other feature you are waiting for that is planned for 0.12.2, or can it just be released?

**Comment by AndyGauge** [comment]
0.12.2 was released 2020-02-20.

The release process is arduous, and has inherent risk.  The reward must outweigh the risk.  

The current changes include two executable bits being removed.  Is that the feature you've been waiting for?

**Comment by mulkieran** [comment]
The change in 44c9240940e974695386cb7b9ab020df1147dbfe was motivated by the fact that it screws up downstream packaging, the change in f8d3bf1c066ea5d2e968ebeea73b47314ff98e51 is just good citizen tidying. In our case, after upgrading to the new release, we moved back down to the prior release, https://github.com/stratis-storage/project/issues/165, as we couldn't do our testing w/ the new release, because some of our testing requires going through the full Fedora packaging process, which fails on version 0.12.2.

**Comment by AndyGauge** [comment]
Ah, so stable here means it works with the packaging.  Got it.  Yeah, I can push out a new version presumably this weekend.

**Comment by Flyking001** [comment]
> Ah, so stable here means it works with the packaging. Got it. Yeah, I can push out a new version presumably this weekend.

Yes，thanks

**Comment by Flyking001** [comment]
Hi，it's been a month. I haven't seen the packaging yet. When will it be pushed out ?

**Comment by AndyGauge** [comment]
can you test v 0.12.3

**Comment by bgilbert** [comment]
0.12.3 showed up [on crates.io](https://crates.io/crates/error-chain), but it doesn't have a [GitHub release](https://github.com/rust-lang-nursery/error-chain/releases), doesn't have a [tag](https://github.com/rust-lang-nursery/error-chain/tags), isn't listed in the [changelog](https://github.com/rust-lang-nursery/error-chain/blob/master/CHANGELOG.md), isn't mentioned in recent [PRs](https://github.com/rust-lang-nursery/error-chain/pulls?q=is%3Apr+is%3Aclosed), and the master branch hasn't had a commit since May 23.  I eventually found [this branch](https://github.com/rust-lang-nursery/error-chain/tree/0.12.3), but still, that's more than a little spooky.

Could you update the various release bits on GitHub to make it easier to learn about the contents of this release?

**Comment by AndyGauge** [comment]
uh... sure.  its a couple executable bits....
